apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "*"
  values:
    controller:
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: default-address-pool
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
    defaultBackend:
      enabled: true
