apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1m
  path: "./manifests/prometheus/conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-repo
