apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitlab-repo
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com:aidaner256/infra-tz.git
  ref:
    branch: main
 