apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  interval: 1m
  path: "./conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitlab
