apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-init-sql
  labels:
    app: myapp
    component: postgres
data:
  init.sql: |
    -- Инициализация базы данных
    CREATE DATABASE IF NOT EXISTS myapp;

    -- Создание таблицы пользователей
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Вставка тестовых данных
    INSERT INTO users (name, email) VALUES 
        ('John Doe', 'john@example.com'),
        ('Jane Smith', 'jane@example.com')
    ON CONFLICT (email) DO NOTHING;
