apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m
  path: "./manifests/ingress-nginx/conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ingress-nginx-repo
