apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: "9.3.1"
    values:
      global:
        hosts:
          domain: gitlab.local.test
          https: false
        ingress:
          enabled: true
          class: nginx
          tls:
            enabled: false
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        registry:
          enabled: false
      nginx-ingress:
        enabled: false
      certmanager:
        install: false
      gitlab:
        gitaly:
          persistence:
            enabled: true
            storageClass: local-path
        gitlab-shell:
          enabled: false
        webservice:
          minReplicas: 1
          maxReplicas: 2
        sidekiq:
          minReplicas: 1
          maxReplicas: 2
        toolbox:
          enabled: false
      postgresql:
        primary:
          persistence:
            enabled: true
            storageClass: local-path
      redis:
        master:
          persistence:
            enabled: true
            storageClass: local-path
      minio:
        persistence:
          enabled: true
          storageClass: local-path
