apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1m
  path: "./manifests/grafana/conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: grafana-repo
