apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-apps
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
  targetNamespace: dev
  wait: true
  timeout: 5m
  retryInterval: 30s
