apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: myapp
    component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: myapp
    component: postgres
