apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: "9.3.1"
    values:
      global:
        hosts:
          domain: gitlab.local.test
        ingress:
          configureCertmanager: false
          tls:
            enabled: false
        registry:
          enabled: false
      certmanager:
        install: false
      gitlab:
        gitaly:
          persistence:
            enabled: false
        gitlab-shell:
          enabled: false
        webservice:
          minReplicas: 1
          maxReplicas: 2
        sidekiq:
          minReplicas: 1
          maxReplicas: 2
        toolbox:
          enabled: false
      postgresql:
        primary:
          persistence:
            enabled: false
      redis:
        master:
          persistence:
            enabled: false
      minio:
        persistence:
          enabled: false
